### ISSUE TITLE
I cant respawn

### ISSUE THREAD

**Issue by FireFoxxo23** [Floris0106/Rereskillable-Rereforked#22]
Minecraft 1.16.5

**Comment by FireFoxxo23** [comment]
[01:17:73] [Server thread/ERROR]: 
[01:17:73] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Player FireFoxxo23 does not have a Skill Model!
	at floris0106.rereskillablerereforked.common.capabilities.SkillModel.lambda$get$0(SkillModel.java:77)
	at floris0106.rereskillablerereforked.common.capabilities.SkillModel$$Lambda$8798/840127183.get(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:282)
	at floris0106.rereskillablerereforked.common.capabilities.SkillModel.get(SkillModel.java:76)
	at floris0106.rereskillablerereforked.common.EventHandler.onPlayerClone(EventHandler.java:194)
	at net.minecraftforge.eventbus.ASMEventHandler_294_EventHandler_onPlayerClone_Clone.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$3127/800722348.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerClone(ForgeEventFactory.java:482)
	at net.minecraft.entity.player.ServerPlayerEntity.func_193104_a(ServerPlayerEntity.java:1109)
	at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:434)
	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:1234)
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34)
	at net.minecraft.network.PacketThreadUtil$$Lambda$8824/1935048.run(Unknown Source)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:130)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$8119/85443343.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Floris0106** [comment]
This is a known issue, a fix is being worked on. Closing as duplicate (of https://github.com/Floris0106/Rereskillable-Rereforked/issues/10)
